# Docker Compose configuration

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: file-manager-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: file-manager-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
    driver: local
  database:
    driver: local
